apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8swebapi
  namespace: aspnetcore
  labels:
    name: k8swebapi
spec:
  replicas: 2
  selector:
    matchLabels:
      name: k8swebapi
  template:
    metadata:
      labels:
        name: k8swebapi
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: k8swebapi
        image: jacklmj/k8swebapi
        ports:
        - containerPort: 80
        imagePullPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: k8swebapi
  namespace: aspnetcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: k8swebapi