apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: aspnetcore
  labels:
    name: webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      name: webapi
  template:
    metadata:
      labels:
        name: webapi
    spec:
      imagePullSecrets:
      - name: regsecret
      containers:
      - name: webapi
        image: webapi
        ports:
        - containerPort: 80
        imagePullPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: webapi
  namespace: aspnetcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: webapi